"""add_format_column_to_focused_channels

Revision ID: 1d6a2386724e
Revises: 548b6b7f449e
Create Date: 2025-08-27 08:08:04.765655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6a2386724e'
down_revision: Union[str, Sequence[str], None] = '548b6b7f449e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add format column as nullable first
    with op.batch_alter_table('focused_channels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format', sa.String(length=20), nullable=True))

    # Populate existing data using channel name parsing logic
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT id, channel_name FROM focused_channels"))
    for row in result:
        channel_id, channel_name = row
        # Extract format from channel name (first word before hyphen)
        format_value = channel_name.split('-')[0] if '-' in channel_name else channel_name
        connection.execute(
            sa.text("UPDATE focused_channels SET format = :format WHERE id = :id"),
            {"format": format_value, "id": channel_id}
        )
    
    # Make the column non-nullable
    with op.batch_alter_table('focused_channels', schema=None) as batch_op:
        batch_op.alter_column('format', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('focused_channels', schema=None) as batch_op:
        batch_op.drop_column('format')

    # ### end Alembic commands ###
