"""Initial bridge database schema

Revision ID: 548b6b7f449e
Revises: 
Create Date: 2025-08-25 08:51:45.512562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548b6b7f449e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('focused_channels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('guild_id', sa.String(length=20), nullable=False),
    sa.Column('channel_id', sa.String(length=20), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'channel_id', name='uq_guild_channel')
    )
    with op.batch_alter_table('focused_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focused_channels_channel_id'), ['channel_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_focused_channels_guild_id'), ['guild_id'], unique=False)

    op.create_table('passes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pass_type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('last_processed_time', sa.DateTime(), nullable=True),
    sa.Column('messages_processed', sa.BigInteger(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('passes', schema=None) as batch_op:
        batch_op.create_index('idx_pass_type_start', ['pass_type', 'start_time'], unique=False)

    op.create_table('discord_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discord_id', sa.String(length=20), nullable=False),
    sa.Column('channel_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=20), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('message_time', sa.DateTime(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('attachment_urls', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['focused_channels.id'], name='fk_discord_post_channel'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discord_posts', schema=None) as batch_op:
        batch_op.create_index('idx_discord_post_message_time', ['message_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_discord_posts_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discord_posts_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discord_posts_discord_id'), ['discord_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_discord_posts_message_time'), ['message_time'], unique=False)

    op.create_table('social_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('discord_post_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_time', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['discord_post_id'], ['discord_posts.id'], name='fk_social_message_discord_post'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('social_messages', schema=None) as batch_op:
        batch_op.create_index('idx_social_message_post_time', ['post_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_messages_discord_post_id'), ['discord_post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_social_messages_post_time'), ['post_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_messages_post_time'))
        batch_op.drop_index(batch_op.f('ix_social_messages_discord_post_id'))
        batch_op.drop_index('idx_social_message_post_time')

    op.drop_table('social_messages')
    with op.batch_alter_table('discord_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discord_posts_message_time'))
        batch_op.drop_index(batch_op.f('ix_discord_posts_discord_id'))
        batch_op.drop_index(batch_op.f('ix_discord_posts_channel_id'))
        batch_op.drop_index(batch_op.f('ix_discord_posts_author_id'))
        batch_op.drop_index('idx_discord_post_message_time')

    op.drop_table('discord_posts')
    with op.batch_alter_table('passes', schema=None) as batch_op:
        batch_op.drop_index('idx_pass_type_start')

    op.drop_table('passes')
    with op.batch_alter_table('focused_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focused_channels_guild_id'))
        batch_op.drop_index(batch_op.f('ix_focused_channels_channel_id'))

    op.drop_table('focused_channels')
    # ### end Alembic commands ###
