"""session source

Revision ID: d46c3129fe0d
Revises: e4c38b1739d5
Create Date: 2025-09-21 13:10:03.796656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd46c3129fe0d'
down_revision: Union[str, Sequence[str], None] = 'e4c38b1739d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('source', sa.String(length=20), nullable=True))
    op.add_column('chat_sessions', sa.Column('source_meta', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_source'), 'chat_sessions', ['source'], unique=False)
    op.alter_column('social_notifications', 'thread_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('tool_calls', 'input_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('tool_calls', 'column_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('tool_results', 'result_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tool_results', 'result_content',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('tool_calls', 'column_names',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tool_calls', 'input_params',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('social_notifications', 'thread_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_chat_sessions_source'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'source_meta')
    op.drop_column('chat_sessions', 'source')
    # ### end Alembic commands ###
