"""social notifications table

Revision ID: e4c38b1739d5
Revises: 05b418fcf4c0
Create Date: 2025-09-13 08:05:38.812056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4c38b1739d5'
down_revision: Union[str, Sequence[str], None] = '05b418fcf4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('post_uri', sa.String(length=255), nullable=False),
    sa.Column('post_cid', sa.String(length=100), nullable=True),
    sa.Column('actor_id', sa.String(length=200), nullable=True),
    sa.Column('actor_handle', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_self', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('root_uri', sa.String(length=255), nullable=True),
    sa.Column('root_cid', sa.String(length=100), nullable=True),
    sa.Column('parent_uri', sa.String(length=255), nullable=True),
    sa.Column('parent_cid', sa.String(length=100), nullable=True),
    sa.Column('thread_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_uri', sa.String(length=255), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'post_uri', 'actor_id', 'reason', name='uq_social_notification_unique')
    )
    op.create_index('idx_social_notification_platform_status_time', 'social_notifications', ['platform', 'status', 'indexed_at'], unique=False)
    op.create_index(op.f('ix_social_notifications_actor_id'), 'social_notifications', ['actor_id'], unique=False)
    op.create_index(op.f('ix_social_notifications_indexed_at'), 'social_notifications', ['indexed_at'], unique=False)
    op.create_index(op.f('ix_social_notifications_platform'), 'social_notifications', ['platform'], unique=False)
    op.create_index(op.f('ix_social_notifications_post_uri'), 'social_notifications', ['post_uri'], unique=False)
    op.create_index(op.f('ix_social_notifications_reason'), 'social_notifications', ['reason'], unique=False)
    op.create_index(op.f('ix_social_notifications_session_id'), 'social_notifications', ['session_id'], unique=False)
    op.create_index(op.f('ix_social_notifications_status'), 'social_notifications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_notifications_status'), table_name='social_notifications')
    op.drop_index(op.f('ix_social_notifications_session_id'), table_name='social_notifications')
    op.drop_index(op.f('ix_social_notifications_reason'), table_name='social_notifications')
    op.drop_index(op.f('ix_social_notifications_post_uri'), table_name='social_notifications')
    op.drop_index(op.f('ix_social_notifications_platform'), table_name='social_notifications')
    op.drop_index(op.f('ix_social_notifications_indexed_at'), table_name='social_notifications')
    op.drop_index(op.f('ix_social_notifications_actor_id'), table_name='social_notifications')
    op.drop_index('idx_social_notification_platform_status_time', table_name='social_notifications')
    op.drop_table('social_notifications')
    # ### end Alembic commands ###
