"""setup cascade deletion of tournament

Revision ID: 0d10e1d0ebdf
Revises: c609b14a4e86
Create Date: 2025-08-10 07:31:53.666892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d10e1d0ebdf'
down_revision: Union[str, Sequence[str], None] = 'c609b14a4e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_cards', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_deck_cards_entry'), type_='foreignkey')
        batch_op.create_foreign_key('fk_deck_cards_entry', 'tournament_entries', ['entry_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_matches_entry'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_matches_opponent_entry'), type_='foreignkey')
        batch_op.create_foreign_key('fk_matches_entry', 'tournament_entries', ['entry_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_matches_opponent_entry', 'tournament_entries', ['opponent_entry_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tournament_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tournament_entries_tournament'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tournament_entries_tournament', 'tournaments', ['tournament_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tournament_entries_tournament', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tournament_entries_tournament'), 'tournaments', ['tournament_id'], ['id'])

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('fk_matches_opponent_entry', type_='foreignkey')
        batch_op.drop_constraint('fk_matches_entry', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_matches_opponent_entry'), 'tournament_entries', ['opponent_entry_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_matches_entry'), 'tournament_entries', ['entry_id'], ['id'])

    with op.batch_alter_table('deck_cards', schema=None) as batch_op:
        batch_op.drop_constraint('fk_deck_cards_entry', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_deck_cards_entry'), 'tournament_entries', ['entry_id'], ['id'])

    # ### end Alembic commands ###
