"""is_land card type

Revision ID: 1a604eff3d98
Revises: e9534b7b55c4
Create Date: 2025-08-12 21:30:01.773127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a604eff3d98'
down_revision: Union[str, Sequence[str], None] = 'e9534b7b55c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_land', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('tournament_entries', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_entries', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('is_land')

    # ### end Alembic commands ###
