"""Remove duplicate indexes and update MetaChange

Revision ID: 710e1fa5c346
Revises: 4eab9a6087ec
Create Date: 2025-08-09 14:18:51.701025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710e1fa5c346'
down_revision: Union[str, Sequence[str], None] = '4eab9a6087ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archetypes', 'companion')
    op.drop_index(op.f('idx_card_name'), table_name='cards')
    op.drop_index(op.f('idx_card_oracle_id'), table_name='cards')
    op.drop_index(op.f('idx_match_pair_id'), table_name='matches')
    op.alter_column('meta_changes', 'change_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('BAN', 'SET_RELEASE', name='changetype'),
               existing_nullable=False)
    op.alter_column('meta_changes', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('meta_changes', 'card_name')
    op.drop_index(op.f('idx_player_normalized_handle'), table_name='players')
    op.drop_index(op.f('idx_entry_archetype'), table_name='tournament_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_entry_archetype'), 'tournament_entries', ['archetype_id'], unique=False)
    op.create_index(op.f('idx_player_normalized_handle'), 'players', ['normalized_handle'], unique=False)
    op.add_column('meta_changes', sa.Column('card_name', sa.VARCHAR(length=200), nullable=True))
    op.alter_column('meta_changes', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('meta_changes', 'change_type',
               existing_type=sa.Enum('BAN', 'SET_RELEASE', name='changetype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_index(op.f('idx_match_pair_id'), 'matches', ['pair_id'], unique=False)
    op.create_index(op.f('idx_card_oracle_id'), 'cards', ['scryfall_oracle_id'], unique=False)
    op.create_index(op.f('idx_card_name'), 'cards', ['name'], unique=False)
    op.add_column('archetypes', sa.Column('companion', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
