"""Add sets and card colors tables

Revision ID: 94be167b4a27
Revises: 69dd28a23263
Create Date: 2025-08-27 14:40:21.489767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94be167b4a27'
down_revision: Union[str, Sequence[str], None] = '69dd28a23263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('set_type', sa.String(length=50), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sets_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_sets_released_at'), ['released_at'], unique=False)

    op.create_table('card_colors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('color', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name='fk_card_colors_card', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id', 'color', name='uq_card_color')
    )
    with op.batch_alter_table('card_colors', schema=None) as batch_op:
        batch_op.create_index('idx_card_color', ['card_id', 'color'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_colors_card_id'), ['card_id'], unique=False)

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colors', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('first_printed_set_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('first_printed_date', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cards_first_printed_date'), ['first_printed_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_first_printed_set_id'), ['first_printed_set_id'], unique=False)
        batch_op.create_foreign_key('fk_card_first_printed_set', 'sets', ['first_printed_set_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_constraint('fk_card_first_printed_set', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cards_first_printed_set_id'))
        batch_op.drop_index(batch_op.f('ix_cards_first_printed_date'))
        batch_op.drop_column('first_printed_date')
        batch_op.drop_column('first_printed_set_id')
        batch_op.drop_column('colors')

    with op.batch_alter_table('card_colors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_colors_card_id'))
        batch_op.drop_index('idx_card_color')

    op.drop_table('card_colors')
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sets_released_at'))
        batch_op.drop_index(batch_op.f('ix_sets_code'))

    op.drop_table('sets')
    # ### end Alembic commands ###
