"""Non nullable scryfall ID

Revision ID: c609b14a4e86
Revises: ee940c2f516d
Create Date: 2025-08-10 07:15:49.818315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c609b14a4e86'
down_revision: Union[str, Sequence[str], None] = 'ee940c2f516d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check for cards with NULL scryfall_oracle_id before making column non-nullable
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT COUNT(*) FROM cards WHERE scryfall_oracle_id IS NULL"))
    null_count = result.fetchone()[0]
    
    if null_count > 0:
        print(f"WARNING: Found {null_count} cards with NULL scryfall_oracle_id")
        confirm = input(f"Delete {null_count} cards with NULL scryfall_oracle_id? (y/N): ")
        if confirm.lower() == 'y':
            connection.execute(sa.text("DELETE FROM cards WHERE scryfall_oracle_id IS NULL"))
            print(f"Deleted {null_count} cards with NULL scryfall_oracle_id")
        else:
            raise Exception("Migration aborted: Cannot make scryfall_oracle_id non-nullable with existing NULL values")
    
    op.drop_table('_alembic_tmp_archetypes')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('scryfall_oracle_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('scryfall_oracle_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    op.create_table('_alembic_tmp_archetypes',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('color', sa.VARCHAR(length=10), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('format_id', sa.VARCHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
