"""rank attribute in tournament entry

Revision ID: e9534b7b55c4
Revises: 0d10e1d0ebdf
Create Date: 2025-08-10 08:53:46.567852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9534b7b55c4'
down_revision: Union[str, Sequence[str], None] = '0d10e1d0ebdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_entries', schema=None) as batch_op:
        batch_op.drop_column('rank')

    # ### end Alembic commands ###
