"""Add format constraint to archetypes

Revision ID: ee940c2f516d
Revises: 689545bc6892
Create Date: 2025-08-09 17:47:36.064600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee940c2f516d'
down_revision: Union[str, Sequence[str], None] = '689545bc6892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archetypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format_id', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_archetypes_format_id'), ['format_id'], unique=False)
        batch_op.drop_constraint('uq_archetype_name', type_='unique')  # Drop old constraint
        batch_op.create_unique_constraint('uq_archetype_format_name', ['format_id', 'name'])
        batch_op.create_foreign_key('fk_archetype_format', 'formats', ['format_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archetypes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_archetype_format', type_='foreignkey')
        batch_op.drop_constraint('uq_archetype_format_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_archetypes_format_id'))
        batch_op.drop_column('format_id')
        batch_op.create_unique_constraint('uq_archetype_name', ['name'])  # Restore old unique constraint on name

    # ### end Alembic commands ###
