"""Add archetype aliases table

Revision ID: f8cce4bcce99
Revises: 94be167b4a27
Create Date: 2025-12-01 14:03:10.279142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8cce4bcce99'
down_revision: Union[str, Sequence[str], None] = '94be167b4a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archetype_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('archetype_id', sa.String(length=36), nullable=False),
    sa.Column('confidence_score', sa.FLOAT(), server_default=sa.text('(1.0)'), nullable=True),
    sa.Column('source', sa.String(), server_default='manual', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['archetype_id'], ['archetypes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias', 'archetype_id', name='uq_alias_archetype_id')
    )
    with op.batch_alter_table('archetype_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archetype_aliases_archetype_id'), ['archetype_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archetype_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archetype_aliases_archetype_id'))

    op.drop_table('archetype_aliases')
    # ### end Alembic commands ###
